### ISSUE TITLE
Support for new factions

### ISSUE THREAD

**Issue by geordanr** [elistevens/xws-spec#13]
If the leaked images for the new core set are indeed real, we may have to add support for the new factions.

Even though the (leaked) rules state that the new factions can be mixed into existing ones (e.g. Resistance is essentially Rebel Alliance), there could be the possibility of pilots being re-released in the new faction (Resistance Han Solo, anyone?).  I suggest an optional `faction` key in the pilot dictionary; if it does not exist, consumers should assume it is the same as the overall faction.  But if present, consumers should use that as a hint to determine which pilot should be used (in the hypothetical Rebel Alliance vs. Resistance Han Solo case).

I believe overall squadron factions should remain restricted to one of the three primary factions, as they are now.

Thoughts?

**Comment by fab7431** [comment]
Hi Geordan,

Just discovered that this morning.
I think that we have to follow the FFG decriptions : 
Primary factions : Rebel - Imperial - Scum
Subfactions : Rebel Alliance - Resistance ; Galactic Empire - First Order ; Scum and Villainy

I think that we have to keep the primary faction at the squad level and the subfaction at the pilot/ship level. The key should be "subfaction".
Make it optional seems strange to me, but for compatibility reason it would be an issue to have it mandatory, but I think it will be better as it is the only way to differenciate Han Solo versus an old Han Solo.

At the builder level, I don't know yet how to handle that, and if I need to put in place an option to build squad with only subfaction ships... (I think so).

**Comment by lhayhurst** [comment]
"Subfaction" is the term used in the leaked rules FWIW.

**Comment by voidstate** [comment]
I agree that it should be at pilot level. I also like "subfaction" name. 😀

**Comment by geordanr** [comment]
Good idea -- subfaction for the pilot level, and keep faction at the top level.

I would be okay with making subfaction be mandatory.

**Comment by fab7431** [comment]
Other point, don't you think that we should change also the faction names in order to be inline with FFG wording ?
Rebel - Imperial - Scum (rebel - imperial - scum)
instead of rebels - empire - scum

**Comment by voidstate** [comment]
Good idea, Fab. Totally agree.

**Comment by voidstate** [comment]
My only concern is that we will be adding quite a lot of new characters to an XWS file if we include subfaction with each pilot. But I guess that cannot be helped.

**Comment by elistevens** [comment]
I agree that we should switch to Rebel - Imperial - Scum, but I disagree that we should start including subfaction.

That should wait until we actually have concrete evidence that it's needed, IMO, because there's no reason to think that we'd actually get the implementation right if we do it ahead of time (maybe it won't be an issue, because they'll call him "General Solo" or w/e). And if it turns out they never do, it's just useless cruft.

**Comment by fab7431** [comment]
Ok, no problem with that, we will see if it is necessary in the future.

**Comment by geordanr** [comment]
The version number needs to be bumped if we're changing to match the primary faction titles.  What will the new version be?  0.3?

**Comment by voidstate** [comment]
0.3 is fine by me.

Are we ready for this?

I think Sozin has already implemented the new names in list juggler and t's causing errors so I'm keen to make a change once we're all happy.

**Comment by fab7431** [comment]
ok for me.

**Comment by lhayhurst** [comment]
sorry for late response!  I'm good with it to.  listjuggler will support the old naming convention as well until everyone migrates.  cheers

**Comment by geordanr** [comment]
I'm good (already implemented, actually >_>).

**Comment by voidstate** [comment]
Does someone who better understands the dark art of Git want to update the spec? :)

Perhaps including support for the legacy names as an optional extra?

**Comment by elistevens** [comment]
Sorry about the delay in getting this up.

The master branch now has v0.3.0, which consists of the following changes:
- Top level factions are now "Rebel" "Imperial" "Scum"
- Exported ship data now includes subfaction (available at the JS API level, not part of the JSON spec)
- Validation function will convert old factions to new
- Slight changes to the README_NAMES.md file to show the new faction info
- Removed the special casing for the old faction names in canonicalization

I've updated the samples, etc. to match.

Assuming that there are no further tweaks needed, I can get this live pretty quickly.

**Comment by voidstate** [comment]
Thanks Eli for making all those changes.

I notice, though, that you are using the full name for subfactions in the JS API (eg. "Rebel Alliance"). Should we perhaps be using the canonicalised version instead? (eg. "rebelalliance"). That would match better with the top-level faction keys.

**Comment by elistevens** [comment]
Since A) there seem to be no game mechanics that rely on it, and B) the YT-1300 has versions in both subfactions, I'm going to remove the "subfaction" key entirely. If it turns out that someone is actually using the data, we can discuss the best approach to reintroduce it.

This will be addressed with XWS 1.0.0, which will be pushed momentarily. Please re-open if there are any remaining details to sort out.
