### ISSUE TITLE
reference data json

### ISSUE THREAD

**Issue by lhayhurst** [elistevens/xws-spec#16]
hey all!

I'm going to be redoing the list builder inside list juggler and wanted to [ditch my implementation](https://github.com/lhayhurst/xwlists/blob/master/xwingmetadata.py) of all the underlying reference data (name, canon name, cost, etc).  I'm getting lazy and want to just consume the xwing reference data from elsewhere -- ideally xws.

For the new builder design I'm going omni design: a single search bar/text entry tool where the user can type in either a faction, ship, pilot, upgrade, ship type, or upgrade type.   It will no almost zero validation of what the user is typing in -- the goal is to quickly bash out text versions of lists, and not actually build (that is what fabs, voidstate, and yasb are for).  

However, given that I'll still have to track point cost (as per the xws spec, costs validation is up to the consumer), I can't be blithely allow two Charadaan Refits for -4 cost :-)  

My first thought was to double check and see if xws already had what I was looking for -- that is, a json payload that had all the reference data. 

{
    "factions": [ {"name": "Rebel Alliance", "xwscanon": 'rebel'}, {...}],
    "ships": [ {"name": "X-Wing", "xwscanon": "xwing", "faction_constraint": ['rebel']}, {...},
    "pilots" : [...],
    "upgrades" : [...]
}

But it doesn't.  

Am I crazy to think that we're all hard coding mostly the same stuff into different formats to bootstrap the builders?  I'd love to join forces with someone else so I don't have to type as much :)  As token of my seriousness, I'll offer up converting my python implementation into a general json reference here on xws!

**Comment by guidokessels** [comment]
I have all this data (and more) in JSON files in its own repository, which I use for my X-Wing Companion app. The repo also has all card images. I've thought about open-sourcing it before but never got around to it.

If you want I can give you access, and if it's what you're looking for I can open-source it :)

**Comment by elistevens** [comment]
The data does exist in the XWS JS as an exported object:

https://github.com/elistevens/xws-spec/blob/master/dist/xws.js

That's not the same as a JSON file, but you can get at it via JS if you bower-install the xws-spec package. Does that meet your needs?

**Comment by lhayhurst** [comment]
hey - yes, that is a good start.  it would be good to have in addition 1) text description of pilots/upgrade abilities, and 2) attribute descriptions of ships (attack dice, defense dice, upgrade slots), 3) attribute descriptions of pilots - ie their pilot skill and which additional upgrade slots they have access to.

guido, do you have any of that?  either way I'd be happy to have access.

cheers


guido:

**Comment by elistevens** [comment]
I end up stripping all of that out of the YASB data. Check out
cards-common.js from Geordan's repo.

**Comment by lhayhurst** [comment]
a fourth thing, which is significantly more complex, is the concept for constraints.  for example rebel faction only, per squad unique constraints, per ship constraint, etc.  this is a slippery slope as you end getting edge cases like chardan refit, the emperor, various titles, etc, and the act of parameterizing the rules system into a meta reference system is probably harder then just implementing the damn thing in code by hand...

**Comment by lhayhurst** [comment]
https://github.com/geordanr/xwing/blob/master/coffeescripts/cards-common.coffee

good tip eli, ty

**Comment by lhayhurst** [comment]
Eli (or geordan), is there a spot where the pilot and upgrade cards text description is provided? ie Howlrunner: "When another friendly ship at Range One is attacking..."

**Comment by lhayhurst** [comment]
hmm, one small issue with geordan's cards-common is that all the hashkeys are using the non-canonicalized names.

**Comment by elistevens** [comment]
I think that all of the english card text is in YASB `coffeescripts/cards-en.coffee`, with parallel stuff in the translations that people have provided.

There is also some data here: https://github.com/guidokessels/xwing-data

But I think that trying to come up with a specification language for list building rules is going to be difficult and fragile with regards to new content from FFG (vs. just coding it, which according to Geordan, is still damn difficult).

Going to close this ticket out, since it's out of scope for XWS.
