### ISSUE TITLE
Canonicalization for new obstacles

### ISSUE THREAD

**Issue by geordanr** [elistevens/xws-spec#17]
We should have canonical names for the asteroids in the new core set.

Do we have an image that matches the one on the back of the squad sheet given out at Worlds?  That would make for a good ordering.

**Comment by fab7431** [comment]
I am very interested in that image as FFG didn't yet upgraded its squadron sheet. Regarding the naming what do you think is we go this way : 
core2-asteroid-0
core2-asteroid-1
...

**Comment by voidstate** [comment]
Good idea. I have no real leanings as to how we do it. Fab's suggestion seems logical...

**Comment by elistevens** [comment]
Note that the current image has no hyphens in the names, but otherwise we're going with Fab's suggestion. I've uploaded a new image with the core2 rocks.

This will be addressed with XWS 1.0.0, which will be pushed momentarily. Please re-open if there are any remaining details to sort out.
