### ISSUE TITLE
Support for Dual Cards

### ISSUE THREAD

**Issue by voidstate** [elistevens/xws-spec#19]
The Mist Hunter preview introduced Dual Cards. Any ideas on how we handle them? Currently both sides will have the same name. Should we be able to differentiate between sides?

![swx41_adaptability-increase](https://cloud.githubusercontent.com/assets/1204122/12916475/aa58571a-cf2a-11e5-811c-c17bc6577834.png)

**Comment by voidstate** [comment]
We probably have to wait until we have the full rules for them. How they are shown in XWS depends on whether you have to decide which way up the card is when you make a squadron, or if you can flip them before each match (or even mid-game).

**Comment by elistevens** [comment]
Since they're chosen at deployment time, I think we can close this out.
