### ISSUE TITLE
Support for damage decks

### ISSUE THREAD

**Issue by fab7431** [elistevens/xws-spec#20]
Hi, as players can now choose their damage decks, you should add optional support for them, the same way we handled obstacles.

**Comment by voidstate** [comment]
Good idea. Do they have official names?

**Comment by fab7431** [comment]
In my builder, I use the following names :
X-wing core set
The Force awakens core set

**Comment by fab7431** [comment]
Correction.
X-wing core set damage deck
The Force awakens damage deck

**Comment by geordanr** [comment]
The FAQ calls them:

Original Core Set Damage Deck
The Force Awakens Core Set Damage Deck

**Comment by fab7431** [comment]
So, we can go with that !

**Comment by voidstate** [comment]
Not the most snappy names... But I guess it doesn't matter if you're only using it once per squadron.

**Comment by elistevens** [comment]
IIRC, we're using "core" and "core2" for rocks, I think that we should be
consistent and use the same here.

"damagedeck": "core",

At the top level of the squad.

**Comment by fab7431** [comment]
Sounds good !

**Comment by elistevens** [comment]
This will be addressed with XWS 1.0.0, which will be pushed momentarily. Please re-open if there are any remaining details to sort out.
