### ISSUE TITLE
"yt2400" vs. "yt2400freighter"?

### ISSUE THREAD

**Issue by elistevens** [elistevens/xws-spec#27]
@geordanr @guidokessels

Geordan mentioned to me that there was some consensus about calling the YT-2400 "yt2400freighter" instead of "yt2400" like the card says, but I don't recall anything about it.

Anyone have an opinion?

**Comment by lhayhurst** [comment]
For some reason we all settled on yt2400freighter, but I can't remember why. I vote on putting freighter at the end, because I am lazy, and I laugh about how a freighter has a hard one maneuver.

**Comment by fab7431** [comment]
I think we should go with that is printed on the card ! Quite frankly I didn't remember why we could have settled other way ... ;-)

**Comment by guidokessels** [comment]
I did a quick check and saw that the Big Three (Voidstate, YASB and Fabs) all use `yt2400freighter`. 

I'd prefer to use `yt2400` as it follows the rule of the spec. But that'd require a lot of updating in different products. It'd be easier to update the spec than to update all squad builders (and perhaps ListJuggler and other products that already expect `yt2400freighter`?) so let's just change the spec to match what's being used right now :)

**Comment by lhayhurst** [comment]
I did some archaelogoy; I think Fergus first used yt2400 freighter, after which I seem to have started using it, and then infected Geordan with the idea in a google chat. Not sure how fabs got bit. Anyways ready to move over to yt2400 whenever.

**Comment by elistevens** [comment]
YASB is currently exporting "yt2400" but Geordan was saying something about how the backend was using something else.

I'd rather not have special cases in the spec without a real reason. All of the current special cases seem to be one of two cases:
- Clarifications of "no really, the exact text on the card" (typically "Adv.").
- Shortening the various upgrade slot types to make the JSON smaller.

This seems like it would be the opposite of the first case.

**Comment by voidstate** [comment]
It's a 2 minute job for me to change it. I'm happy to go with whatever you guys decide.

**Comment by lhayhurst** [comment]
I'm ready to switch over to, but we should all synchronize on it, because vassal league and regional season is in full force now and there is a steady drip drip of xws imports.

**Comment by kingargyle** [comment]
If the XWING-Data files are updated to match, I won't have any change to do with XStreamer as I rely on the lookup data in the xwing-data ship, pilot, and upgrade cards to find the real names.

**Comment by geordanr** [comment]
I'm fine with switching over.  I'm largely flexible on time, so whenever's convenient (for Vassal League or whatever).

**Comment by elistevens** [comment]
Since most of the interesting stuff happens on the weekend, I'd propose Tues. or Weds. to do the switch over.

**Comment by lhayhurst** [comment]
Agree. Let's go with whatever time works for Fergus since he's on the earliest timezone.

**Comment by guidokessels** [comment]
Shall we move forward with this? I suggest we switch sometime this week or next.

**Comment by voidstate** [comment]
Is tomorrow (22nd) too soon?

**Comment by lhayhurst** [comment]
Works for me. hey, fergus, while you're here, I've been emailing you about this but I think I'm getting spam filtered. Your xws for the rebel tie fighter is wrong -- you have it as sabinestiefighter and it should be tiefighter, see http://xwing-builder.co.uk/xws/660354#view=full . Can you fix it? We're getting once a day questions about it now in both juggler and vassal league. cheers

**Comment by geordanr** [comment]
I can do the switchover tonight.

**Comment by fab7431** [comment]
I am on vacation, I will be able to make the change only  next monday.

**Comment by voidstate** [comment]
Ok. Let's make it next Monday. I'll set a reminder and do it later in the day so there's as much synchronisation as possible. Around 4pm GMT.

**Comment by voidstate** [comment]
Lyle - sorry about the delay. I've been putting it off because it requires some rewriting of the XWS import code. It should be outputting OK now. 😃

**Comment by voidstate** [comment]
It's changed on my squadron builder now. 👍

**Comment by fab7431** [comment]
Done on my side also !

**Comment by kingargyle** [comment]
I'll look this weekend to update the XStreamer data files to sync with the new xwing-data files.

**Comment by guidokessels** [comment]
@kingargyle There's no need, xwing-data always used `yt2400 so it should already be correct` :)

**Comment by geordanr** [comment]
Go team!

**Comment by lhayhurst** [comment]
List Juggler is updated

**Comment by guidokessels** [comment]
🎉

**Comment by geordanr** [comment]
Should this ticket be closed then, or is there anything else outstanding?

**Comment by kingargyle** [comment]
@guidokessels excellent.  I shouldn't need to do anything then from the XStreamer side of things.

**Comment by elistevens** [comment]
Looks like the builders, listjuggler, and xwing-data are all using `yt2400` now. Going to close the issue. 

Reopen if there's still something that needs attention.
