### ISSUE TITLE
Quick Build xws IDs

### ISSUE THREAD

**Issue by danrs** [elistevens/xws-spec#50]
The xws spec does not currently support quick builds. I'd like to add this in so that squadron builders can support quick build squadrons. This would also be useful for digital quick build drafts, if anyone decides to build those.

I'm currently working on adding the quick build data to https://github.com/guidokessels/xwing-data2, so I thought it'd be useful to decide on a canonical naming scheme and data structure for quick builds. I'll add a link to this issue once I have a PR up on guido's repo.

As per the [quick build PDFs](https://www.fantasyflightgames.com/en/products/x-wing-second-edition/), each quick build has a threat level and one or more pilots, each with zero or more upgrades. My draft quick build specification is shown below. Let me know what you think.

-------------------------------------------------------------------------------------------------------
**Quick Build Squadron Attributes**

| Requirement | Key | Type | Notes |
| --- | --- | --- | --- |
| Mandatory | cards | Array | List of quick build cards, see below |
| Optional | faction | Array | Canonicalized faction name. Optional in case of mixed-faction drafts(?) |
Optional | name | String | Human-readable squadron name.
Optional | description | String | Text description or notes for the squadron.
Optional | obstacles | Array | Array of three Strings, each being an identifier for the obstacle chosen for tournament use.
Optional | threat | Integer | Total threat cost of the squadron. SHOULD be ignored by importing applications unless the XWS source is trusted.
Ignored | vendor | Dictionary | An object used to store vendor-specific data

**Quick Build Card Attributes**

Requirement | Key | Type | Notes
-- | -- | -- | --
Mandatory | id | String | Canonicalized quick build identifier.
Mandatory | pilots | Array | List of one or more pilots
Optional | threat | Integer | Total threat cost of the quick build card. SHOULD be ignored by importing applications unless the XWS source is trusted.
Ignored | vendor | Dictionary | An object used to store vendor-specific data; see above.

**Quick Build canonicalized ID**
1. Follow the existing rules to create canonicalised names for each pilot.
2. If more then one pilot, join canonicalised pilot names separated by a dash (`"pilot1-pilot2"`). Pilot order should be verified against [https://github.com/guidokessels/xwing-data2](https://github.com/guidokessels/xwing-data2), or against the FFG PDF if the former has no data.
3. Prepend the `"quickbuild-"` prefix. Note: I considered making this a suffix to remain in line with the current spec behaviour, but I prefer it as a prefix to make quick build IDs visually distinct and to prevent the `"quickbuild"` string getting muddled up with other suffixes. It is there to illustrate ID type rather than to avoid collisions so I think it makes sense to make it a prefix instead of a suffix.

Examples:
`"quickbuild-biggsdarklighter"`
`"quickbuild-lothalrebel-zeborrelios-sheathipedeclassshuttle"`
`"quickbuild-phoenixsquadronpilot-phoenixsquadronpilot"`

**Comment by elistevens** [comment]
Isn't the end result of a quickbuild list a set of pilot cards, each with some upgrades? That fits in XWS fine without change. The whole "2 pilots for 3 threat" means that the per-pilot points aren't going to work unless you're okay with saying 1.5 points each (which doesn't really capture the fact that you had to buy them as a group), but the top-level points would be fine.

I think it makes sense to avoid trying to put the listbuilding rules into XWS, and instead focus on the output: a list of pilots with upgrades attached. Keep the rules in the builder application, IMO.

Are you in the tech channel on slack? I think that this should probably be discussed more widely, or at least we should get @guidokessels to chime in.  :)

**Comment by danrs** [comment]
Yep, I'm in the #dev channel on slack. I've already been chatting with
guido about it a bit there already, but I didn't know you were in that
channel as well.

I agree with your points for the most part, but I'll continue the
discussion on slack. We can post a resolution here once we make a decision.

**Comment by guidokessels** [comment]
@danrs The `#dev` and `#tech` channels are different channels. Are you on the vassal league Slack? I can invite you to the #tech channel there. If you're not on that Slack sign up here: https://xwingvassalleagueslack.herokuapp.com/ and let me know so I can invite you to the channel.

I don't think the quickbuilds need to be a part of XWS. They are basically small squads and the current XWS spec already works for this. If you do want to have a collection of all quickbuilds then feel free to put them in xwing-data (as you already started doing). I guess a format like this would work:

```json

**Comment by danrs** [comment]
My apologies, I didn't realise those channels were different. I've just
joined the vassal league slack.

**Comment by danrs** [comment]
Closing this issue as it does not match the intent of the xws-spec. In short, xws-spec should not contain information about squad type or legality, it should just contain a list of pilots and upgrades.

If you have arrived here, like me, wondering how quick builds can be supported in squad builders when they are not recognised by xws-spec, read on for some suggestions.

A quick build list can be exported as valid xws by exporting it as a list of pilots and upgrades. A quick build card can be exported by exporting it as a list of pilots and upgrades. Remember in both cases that the `points` field is optional and that list legality is irrelevant to xws data.

Importing is more difficult, and import methods are left to the application developer. If you wish to support quick builds (especially in the case of streaming software) it may be easiest to accept all incoming xws data, including builds which would be illegal in some formats. Alternately, the importing software could allow importers to specify the format of data being imported (extended, quick build, second edition, or any other format) using a drop-down menu or something.

Also note that quick build data will be added to Guido's xws-data2 repository.
