### ISSUE TITLE
Validator and scheme still beeing on 1.0.0

### ISSUE THREAD

**Issue by Patschke** [elistevens/xws-spec#51]
The linked validator http://elistevens.github.io/xws-spec/ will not work for 2.0.0

**Comment by guidokessels** [comment]
@elistevens Perhaps we should update it to link to http://xhud.sirjorj.com/xwing.cgi/validator2 ?

**Comment by elistevens** [comment]
Updated the link.

FYI, my intent is still to fold all of the README.md text into xwing-data2, and essentially deprecate this entire repo (leaving behind just a short note with a link to xwing-data2).
