### ISSUE TITLE
Schema file conflicts the outlined spec

### ISSUE THREAD

**Issue by minsis** [elistevens/xws-spec#53]
The json schema file doesn't seem to match the new 2.0 rules?

Specifically the schema file still shows name and ship for the pilots, but the 2.0 spec is supposed to be a combined id only.

It seems some apps are starting to have conflicts with exported data like this and still calling it xws valid. One app iOS app I tried exported the pilots out with id and ship, but the id didn't match what is outlined in the spec.

**Comment by elistevens** [comment]
Oh, yeah, that's not had any volunteers update it for 2e. It was donated by someone during the 1e days; jsonschema isn't something I'm familiar with. I wasn't even aware that it was being used.

I'm not actively maintaining the repo these days (see the list of closed pull requests for people who are), but I can either delete it, or if you've got the time/energy/friends to get the file updated properly, I'll merge a PR.

**Comment by minsis** [comment]
Ok I'll probably give it a shot at some point.

So is there a discord or something for discussing xws. I would like to get some ideas on the fact that people seem to be mixing 1.0.0 and 2.0.0 specs unless I'm missing something.

**Comment by elistevens** [comment]
Yeah, if you log into the x-wing vassal league slack channel at xwvl.slack.com and ping me there, I can invite you to the channel where most of the discussion happens.
